<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Versioning & SourceLink -->
  <ItemGroup>
    <GlobalPackageReference Include="ThisAssembly.AssemblyInfo" Version="" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="" />
    <GlobalPackageReference Include="MinVer" Version="" />
  </ItemGroup>
</Project>
